version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Building the project..."
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - "**/*"
